# Generated by Django 3.2 on 2023-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('yesterday_price', models.FloatField()),
                ('start_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('rate_of_change', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('percentage_diff', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stocks_stockinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stocks_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('portfolio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
            ],
            options={
                'db_table': 'user_stocks',
                'managed': False,
            },
        ),
    ]
