# Generated by Django 3.2 on 2023-06-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userpw',
        ),
    ]
