# Generated by Django 3.2 on 2023-06-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20230629_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userpw',
            new_name='username',
        ),
    ]
