# Generated by Django 3.2 on 2023-08-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20230629_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('portfolio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
            ],
            options={
                'db_table': 'user_stocks',
                'managed': False,
            },
        ),
    ]
