# Generated by Django 3.2 on 2023-08-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_userstocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
