# Generated by Django 3.2 on 2023-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='last_price_yesterday',
            new_name='start_price',
        ),
        migrations.RenameField(
            model_name='stockinfo',
            old_name='start_price_today',
            new_name='yesterday_price',
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='percentage_diff',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
